cleanupPeriodDays: 20
env:
  SOME_VAR: some_value
  SOME_OTHER_VAR: some_value
includeCoAuthoredBy: false
permissions:
  allow:
    - Bash(*)
    - WebFetch(*)
    - WebSearch(*)
  deny: []
  additionalDirectories:
    - '../todo'
  defaultMode: acceptEdits
hooks:
  Stop:
    - hooks:
      - type: command
        command: '.claude/hooks/step-complete.sh'
  UserInputRequired:
    - hooks:
      - type: command
        command: '.claude/hooks/user-input-required.sh'
